# @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.
# Shared server<->client physics tuning (single source of truth).
# Use via: const Tuning = preload("res://scripts/tuning.gd")
extends RefCounted

static var PACE_SCALE := 2.0
static var MASS := 1300.0
static var INERTIA_X := 3400.0
static var INERTIA_Y := 3200.0
static var INERTIA_Z := 2800.0
static var COM_Y := -0.4
static var GRAVITY := 22.0
static var THROTTLE_FORCE := 29000.0
static var REVERSE_FORCE := 5000.0
static var BRAKE_FORCE := 8000.0
static var BRAKE_MIN_SPEED := 0.5
static var NORMAL_LINEAR_DAMPING := 0.25
static var DRIFT_LINEAR_DAMPING := 0.15
static var DRIFT_MIN_SPEED := 1.5
static var MAX_TURN_RATE_GRIP := 1.2
static var MAX_TURN_RATE_DRIFT := 4.6
static var STEER_P_GAIN := 25000.0
static var GRIP_LAT_ACCEL := 18.0
static var DRIFT_REDIRECT_RATE := 3.0
static var DRIFT_FLOOR_SPEED := 10.0
static var DRIFT_SPEED_PENALTY := 0.6
static var SLIP_BREAK_DEG := 18.0
static var SLIP_BREAK_HARD_DEG := 5.0
static var DRIFT_EFFORT_SPEED_REF := 6.0
static var SLIP_EXIT_DEG := 8.0
static var DRIFT_FLICK_RATE := 5.5
static var DRIFT_FLICK_BLEND := 0.6
static var GRIP_BLEND_RATE := 6.0
static var GRIP_BLEND_EXIT_RATE := 3.5
static var SPIN_GUARD_DEG := 68.0
static var SPIN_LIMIT_DEG := 90.0
static var SPIN_RESTORE_RATE := 3.0
static var UPRIGHT_GAIN := 120000.0
static var UPRIGHT_DAMP := 42000.0
static var GROUND_ALIGN_MIN_NY := 0.35
static var SUSP_REST_LEN := 0.9
static var SUSP_MAX_LEN := 1.4
static var SUSP_STIFFNESS := 82000.0
static var SUSP_DAMP := 6000.0
static var AIRROLL_RANGE := 40.0
static var AIRROLL_AIM_LATERAL := 1.0
static var AIRROLL_PULL_SPEED := 45.0
static var AIRROLL_RECOVER_TIME := 0.45
static var AIRROLL_RECOVER_GAIN := 320000.0
static var AIRROLL_RECOVER_DAMP := 40000.0
static var AIRROLL_SPIN := 13.0
static var AIRROLL_DODGE_SPEED := 35.0
static var COYOTE_GROUND_SECS := 0.1
static var JUMP_SPEED := 13.0
static var MOTION_DIRECTION_EPSILON := 0.25
static var BOOST_CHARGE_RATE := 0.11
static var BOOST_CHARGE_ANGLE_RATE := 0.36
static var BOOST_CHARGE_ANGLE_REF_DEG := 35.0
static var BOOST_CHARGE_KNEE := 0.667
static var BOOST_CHARGE_TOP_FACTOR := 0.25
static var BOOST_CHARGE_DECAY := 2.0
static var BOOST_CHARGE_MIN := 0.15
static var BOOST_PEAK_BONUS := 23.0
static var BOOST_DURATION := 1.5
static var BOOST_ALIGN_THRESHOLD_COS := 0.9781476
static var BOOST_PENDING_TIMEOUT := 1.5
static var BOOST_SUSTAIN_FORCE := 33000.0
static var CRUISE_SPEED := 116.0
static var TURBO_PEAK_SPEED := 174.0
static var TURBO_FORCE := 60000.0
static var TURBO_CHARGE_RATE := 0.04
static var TURBO_CHARGE_ANGLE_RATE := 0.15
static var TURBO_DRAIN_RATE := 0.5
static var LAUNCH_WINDOW := 0.4
static var LAUNCH_SHARPNESS := 1.3
static var LAUNCH_SPEED := 64.0
static var PAD_BOOST_SCALE := 0.5

# [name, default_value, section] for the gameplay-tweak panel.
const TWEAKABLE := [
	['PACE_SCALE', 2.0, 'General'],
	['MASS', 1300.0, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['INERTIA_X', 3400.0, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['INERTIA_Y', 3200.0, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['INERTIA_Z', 2800.0, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['COM_Y', -0.4, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['GRAVITY', 22.0, 'Car body (mirrored in lobby.rs MassProperties + player.gd _ready)'],
	['THROTTLE_FORCE', 29000.0, 'Drive / brake forces'],
	['REVERSE_FORCE', 5000.0, 'Drive / brake forces'],
	['BRAKE_FORCE', 8000.0, 'Drive / brake forces'],
	['BRAKE_MIN_SPEED', 0.5, 'Drive / brake forces'],
	['NORMAL_LINEAR_DAMPING', 0.25, 'Damping'],
	['DRIFT_LINEAR_DAMPING', 0.15, 'Damping'],
	['DRIFT_MIN_SPEED', 1.5, 'Damping'],
	['MAX_TURN_RATE_GRIP', 1.2, 'Steering / lateral traction'],
	['MAX_TURN_RATE_DRIFT', 4.6, 'Steering / lateral traction'],
	['STEER_P_GAIN', 25000.0, 'Steering / lateral traction'],
	['GRIP_LAT_ACCEL', 18.0, 'Steering / lateral traction'],
	['DRIFT_REDIRECT_RATE', 3.0, 'Steering / lateral traction'],
	['DRIFT_FLOOR_SPEED', 10.0, 'Drift state machine'],
	['DRIFT_SPEED_PENALTY', 0.6, 'Drift state machine'],
	['SLIP_BREAK_DEG', 18.0, 'Drift state machine'],
	['SLIP_BREAK_HARD_DEG', 5.0, 'Drift state machine'],
	['DRIFT_EFFORT_SPEED_REF', 6.0, 'Drift state machine'],
	['SLIP_EXIT_DEG', 8.0, 'Drift state machine'],
	['DRIFT_FLICK_RATE', 5.5, 'Drift state machine'],
	['DRIFT_FLICK_BLEND', 0.6, 'Drift state machine'],
	['GRIP_BLEND_RATE', 6.0, 'Drift state machine'],
	['GRIP_BLEND_EXIT_RATE', 3.5, 'Drift state machine'],
	['SPIN_GUARD_DEG', 68.0, 'Anti-spin'],
	['SPIN_LIMIT_DEG', 90.0, 'Anti-spin'],
	['SPIN_RESTORE_RATE', 3.0, 'Anti-spin'],
	['UPRIGHT_GAIN', 120000.0, 'Uprighting assist (grounded only)'],
	['UPRIGHT_DAMP', 42000.0, 'Uprighting assist (grounded only)'],
	['GROUND_ALIGN_MIN_NY', 0.35, 'Uprighting assist (grounded only)'],
	['SUSP_REST_LEN', 0.9, 'Raycast suspension (replaces the old ground-stick + anti-bounce)'],
	['SUSP_MAX_LEN', 1.4, 'Raycast suspension (replaces the old ground-stick + anti-bounce)'],
	['SUSP_STIFFNESS', 82000.0, 'Raycast suspension (replaces the old ground-stick + anti-bounce)'],
	['SUSP_DAMP', 6000.0, 'Raycast suspension (replaces the old ground-stick + anti-bounce)'],
	['AIRROLL_RANGE', 40.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_AIM_LATERAL', 1.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_PULL_SPEED', 45.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_RECOVER_TIME', 0.45, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_RECOVER_GAIN', 320000.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_RECOVER_DAMP', 40000.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_SPIN', 13.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['AIRROLL_DODGE_SPEED', 35.0, 'Air-roll / surface-recover (the "tonneau", first pass)'],
	['COYOTE_GROUND_SECS', 0.1, 'Grounding / jump'],
	['JUMP_SPEED', 13.0, 'Grounding / jump'],
	['MOTION_DIRECTION_EPSILON', 0.25, 'Grounding / jump'],
	['BOOST_CHARGE_RATE', 0.11, 'Drift boost'],
	['BOOST_CHARGE_ANGLE_RATE', 0.36, 'Drift boost'],
	['BOOST_CHARGE_ANGLE_REF_DEG', 35.0, 'Drift boost'],
	['BOOST_CHARGE_KNEE', 0.667, 'Drift boost'],
	['BOOST_CHARGE_TOP_FACTOR', 0.25, 'Drift boost'],
	['BOOST_CHARGE_DECAY', 2.0, 'Drift boost'],
	['BOOST_CHARGE_MIN', 0.15, 'Drift boost'],
	['BOOST_PEAK_BONUS', 23.0, 'Drift boost'],
	['BOOST_DURATION', 1.5, 'Drift boost'],
	['BOOST_ALIGN_THRESHOLD_COS', 0.9781476, 'Drift boost'],
	['BOOST_PENDING_TIMEOUT', 1.5, 'Drift boost'],
	['BOOST_SUSTAIN_FORCE', 33000.0, 'Drift boost'],
	['CRUISE_SPEED', 116.0, 'Cruise / turbo'],
	['TURBO_PEAK_SPEED', 174.0, 'Cruise / turbo'],
	['TURBO_FORCE', 60000.0, 'Cruise / turbo'],
	['TURBO_CHARGE_RATE', 0.04, 'Cruise / turbo'],
	['TURBO_CHARGE_ANGLE_RATE', 0.15, 'Cruise / turbo'],
	['TURBO_DRAIN_RATE', 0.5, 'Cruise / turbo'],
	['LAUNCH_WINDOW', 0.4, 'Launch (rocket start)'],
	['LAUNCH_SHARPNESS', 1.3, 'Launch (rocket start)'],
	['LAUNCH_SPEED', 64.0, 'Launch (rocket start)'],
	['PAD_BOOST_SCALE', 0.5, 'Launch (rocket start)'],
]

static func apply_overrides(ov: Dictionary) -> void:
	PACE_SCALE = ov.get('PACE_SCALE', 2.0)
	MASS = ov.get('MASS', 1300.0)
	INERTIA_X = ov.get('INERTIA_X', 3400.0)
	INERTIA_Y = ov.get('INERTIA_Y', 3200.0)
	INERTIA_Z = ov.get('INERTIA_Z', 2800.0)
	COM_Y = ov.get('COM_Y', -0.4)
	GRAVITY = ov.get('GRAVITY', 22.0)
	THROTTLE_FORCE = ov.get('THROTTLE_FORCE', 14_500.0 * PACE_SCALE)
	REVERSE_FORCE = ov.get('REVERSE_FORCE', 2_500.0 * PACE_SCALE)
	BRAKE_FORCE = ov.get('BRAKE_FORCE', 4_000.0 * PACE_SCALE)
	BRAKE_MIN_SPEED = ov.get('BRAKE_MIN_SPEED', 0.5)
	NORMAL_LINEAR_DAMPING = ov.get('NORMAL_LINEAR_DAMPING', 0.25)
	DRIFT_LINEAR_DAMPING = ov.get('DRIFT_LINEAR_DAMPING', 0.15)
	DRIFT_MIN_SPEED = ov.get('DRIFT_MIN_SPEED', 1.5)
	MAX_TURN_RATE_GRIP = ov.get('MAX_TURN_RATE_GRIP', 1.2)
	MAX_TURN_RATE_DRIFT = ov.get('MAX_TURN_RATE_DRIFT', 4.6)
	STEER_P_GAIN = ov.get('STEER_P_GAIN', 25_000.0)
	GRIP_LAT_ACCEL = ov.get('GRIP_LAT_ACCEL', 9.0 * PACE_SCALE)
	DRIFT_REDIRECT_RATE = ov.get('DRIFT_REDIRECT_RATE', 3.0)
	DRIFT_FLOOR_SPEED = ov.get('DRIFT_FLOOR_SPEED', 10.0)
	DRIFT_SPEED_PENALTY = ov.get('DRIFT_SPEED_PENALTY', 0.6)
	SLIP_BREAK_DEG = ov.get('SLIP_BREAK_DEG', 18.0)
	SLIP_BREAK_HARD_DEG = ov.get('SLIP_BREAK_HARD_DEG', 5.0)
	DRIFT_EFFORT_SPEED_REF = ov.get('DRIFT_EFFORT_SPEED_REF', 6.0)
	SLIP_EXIT_DEG = ov.get('SLIP_EXIT_DEG', 8.0)
	DRIFT_FLICK_RATE = ov.get('DRIFT_FLICK_RATE', 5.5)
	DRIFT_FLICK_BLEND = ov.get('DRIFT_FLICK_BLEND', 0.6)
	GRIP_BLEND_RATE = ov.get('GRIP_BLEND_RATE', 6.0)
	GRIP_BLEND_EXIT_RATE = ov.get('GRIP_BLEND_EXIT_RATE', 3.5)
	SPIN_GUARD_DEG = ov.get('SPIN_GUARD_DEG', 68.0)
	SPIN_LIMIT_DEG = ov.get('SPIN_LIMIT_DEG', 90.0)
	SPIN_RESTORE_RATE = ov.get('SPIN_RESTORE_RATE', 3.0)
	UPRIGHT_GAIN = ov.get('UPRIGHT_GAIN', 120_000.0)
	UPRIGHT_DAMP = ov.get('UPRIGHT_DAMP', 42_000.0)
	GROUND_ALIGN_MIN_NY = ov.get('GROUND_ALIGN_MIN_NY', 0.35)
	SUSP_REST_LEN = ov.get('SUSP_REST_LEN', 0.9)
	SUSP_MAX_LEN = ov.get('SUSP_MAX_LEN', 1.4)
	SUSP_STIFFNESS = ov.get('SUSP_STIFFNESS', 82_000.0)
	SUSP_DAMP = ov.get('SUSP_DAMP', 6_000.0)
	AIRROLL_RANGE = ov.get('AIRROLL_RANGE', 40.0)
	AIRROLL_AIM_LATERAL = ov.get('AIRROLL_AIM_LATERAL', 1.0)
	AIRROLL_PULL_SPEED = ov.get('AIRROLL_PULL_SPEED', 45.0)
	AIRROLL_RECOVER_TIME = ov.get('AIRROLL_RECOVER_TIME', 0.45)
	AIRROLL_RECOVER_GAIN = ov.get('AIRROLL_RECOVER_GAIN', 320_000.0)
	AIRROLL_RECOVER_DAMP = ov.get('AIRROLL_RECOVER_DAMP', 40_000.0)
	AIRROLL_SPIN = ov.get('AIRROLL_SPIN', 13.0)
	AIRROLL_DODGE_SPEED = ov.get('AIRROLL_DODGE_SPEED', 35.0)
	COYOTE_GROUND_SECS = ov.get('COYOTE_GROUND_SECS', 0.10)
	JUMP_SPEED = ov.get('JUMP_SPEED', 13.0)
	MOTION_DIRECTION_EPSILON = ov.get('MOTION_DIRECTION_EPSILON', 0.25)
	BOOST_CHARGE_RATE = ov.get('BOOST_CHARGE_RATE', 0.11)
	BOOST_CHARGE_ANGLE_RATE = ov.get('BOOST_CHARGE_ANGLE_RATE', 0.36)
	BOOST_CHARGE_ANGLE_REF_DEG = ov.get('BOOST_CHARGE_ANGLE_REF_DEG', 35.0)
	BOOST_CHARGE_KNEE = ov.get('BOOST_CHARGE_KNEE', 0.667)
	BOOST_CHARGE_TOP_FACTOR = ov.get('BOOST_CHARGE_TOP_FACTOR', 0.25)
	BOOST_CHARGE_DECAY = ov.get('BOOST_CHARGE_DECAY', 2.0)
	BOOST_CHARGE_MIN = ov.get('BOOST_CHARGE_MIN', 0.15)
	BOOST_PEAK_BONUS = ov.get('BOOST_PEAK_BONUS', 11.5 * PACE_SCALE)
	BOOST_DURATION = ov.get('BOOST_DURATION', 1.5)
	BOOST_ALIGN_THRESHOLD_COS = ov.get('BOOST_ALIGN_THRESHOLD_COS', 0.9781476)
	BOOST_PENDING_TIMEOUT = ov.get('BOOST_PENDING_TIMEOUT', 1.5)
	BOOST_SUSTAIN_FORCE = ov.get('BOOST_SUSTAIN_FORCE', 16_500.0 * PACE_SCALE)
	CRUISE_SPEED = ov.get('CRUISE_SPEED', THROTTLE_FORCE / (1000.0 * NORMAL_LINEAR_DAMPING))
	TURBO_PEAK_SPEED = ov.get('TURBO_PEAK_SPEED', 1.5 * CRUISE_SPEED)
	TURBO_FORCE = ov.get('TURBO_FORCE', 30_000.0 * PACE_SCALE)
	TURBO_CHARGE_RATE = ov.get('TURBO_CHARGE_RATE', 0.04)
	TURBO_CHARGE_ANGLE_RATE = ov.get('TURBO_CHARGE_ANGLE_RATE', 0.15)
	TURBO_DRAIN_RATE = ov.get('TURBO_DRAIN_RATE', 0.5)
	LAUNCH_WINDOW = ov.get('LAUNCH_WINDOW', 0.40)
	LAUNCH_SHARPNESS = ov.get('LAUNCH_SHARPNESS', 1.3)
	LAUNCH_SPEED = ov.get('LAUNCH_SPEED', 32.0 * PACE_SCALE)
	PAD_BOOST_SCALE = ov.get('PAD_BOOST_SCALE', 0.5)

static func reset() -> void:
	apply_overrides({})
