// @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.
// Shared server<->client physics tuning (single source of truth).
#![allow(dead_code)]
use std::collections::HashMap;

pub const PACE_SCALE: f64 = 2.0;
pub const MASS: f64 = 1300.0;
pub const INERTIA_X: f64 = 3400.0;
pub const INERTIA_Y: f64 = 3200.0;
pub const INERTIA_Z: f64 = 2800.0;
pub const COM_Y: f64 = -0.4;
pub const GRAVITY: f64 = 22.0;
pub const THROTTLE_FORCE: f64 = 14_500.0 * PACE_SCALE;
pub const REVERSE_FORCE: f64 = 2_500.0 * PACE_SCALE;
pub const BRAKE_FORCE: f64 = 4_000.0 * PACE_SCALE;
pub const BRAKE_MIN_SPEED: f64 = 0.5;
pub const NORMAL_LINEAR_DAMPING: f64 = 0.25;
pub const DRIFT_LINEAR_DAMPING: f64 = 0.15;
pub const DRIFT_MIN_SPEED: f64 = 1.5;
pub const MAX_TURN_RATE_GRIP: f64 = 1.2;
pub const MAX_TURN_RATE_DRIFT: f64 = 4.6;
pub const STEER_P_GAIN: f64 = 25_000.0;
pub const GRIP_LAT_ACCEL: f64 = 9.0 * PACE_SCALE;
pub const DRIFT_REDIRECT_RATE: f64 = 3.0;
pub const DRIFT_FLOOR_SPEED: f64 = 10.0;
pub const DRIFT_SPEED_PENALTY: f64 = 0.6;
pub const SLIP_BREAK_DEG: f64 = 18.0;
pub const SLIP_BREAK_HARD_DEG: f64 = 5.0;
pub const DRIFT_EFFORT_SPEED_REF: f64 = 6.0;
pub const SLIP_EXIT_DEG: f64 = 8.0;
pub const DRIFT_FLICK_RATE: f64 = 5.5;
pub const DRIFT_FLICK_BLEND: f64 = 0.6;
pub const GRIP_BLEND_RATE: f64 = 6.0;
pub const GRIP_BLEND_EXIT_RATE: f64 = 3.5;
pub const SPIN_GUARD_DEG: f64 = 68.0;
pub const SPIN_LIMIT_DEG: f64 = 90.0;
pub const SPIN_RESTORE_RATE: f64 = 3.0;
pub const UPRIGHT_GAIN: f64 = 120_000.0;
pub const UPRIGHT_DAMP: f64 = 42_000.0;
pub const GROUND_ALIGN_MIN_NY: f64 = 0.35;
pub const SUSP_REST_LEN: f64 = 0.9;
pub const SUSP_MAX_LEN: f64 = 1.4;
pub const SUSP_STIFFNESS: f64 = 82_000.0;
pub const SUSP_DAMP: f64 = 6_000.0;
pub const AIRROLL_RANGE: f64 = 40.0;
pub const AIRROLL_AIM_LATERAL: f64 = 1.0;
pub const AIRROLL_PULL_SPEED: f64 = 45.0;
pub const AIRROLL_RECOVER_TIME: f64 = 0.45;
pub const AIRROLL_RECOVER_GAIN: f64 = 320_000.0;
pub const AIRROLL_RECOVER_DAMP: f64 = 40_000.0;
pub const AIRROLL_SPIN: f64 = 13.0;
pub const AIRROLL_DODGE_SPEED: f64 = 35.0;
pub const COYOTE_GROUND_SECS: f64 = 0.10;
pub const JUMP_SPEED: f64 = 13.0;
pub const MOTION_DIRECTION_EPSILON: f64 = 0.25;
pub const BOOST_CHARGE_RATE: f64 = 0.11;
pub const BOOST_CHARGE_ANGLE_RATE: f64 = 0.36;
pub const BOOST_CHARGE_ANGLE_REF_DEG: f64 = 35.0;
pub const BOOST_CHARGE_KNEE: f64 = 0.667;
pub const BOOST_CHARGE_TOP_FACTOR: f64 = 0.25;
pub const BOOST_CHARGE_DECAY: f64 = 2.0;
pub const BOOST_CHARGE_MIN: f64 = 0.15;
pub const BOOST_PEAK_BONUS: f64 = 11.5 * PACE_SCALE;
pub const BOOST_DURATION: f64 = 1.5;
pub const BOOST_ALIGN_THRESHOLD_COS: f64 = 0.9781476;
pub const BOOST_PENDING_TIMEOUT: f64 = 1.5;
pub const BOOST_SUSTAIN_FORCE: f64 = 16_500.0 * PACE_SCALE;
pub const CRUISE_SPEED: f64 = THROTTLE_FORCE / (1000.0 * NORMAL_LINEAR_DAMPING);
pub const TURBO_PEAK_SPEED: f64 = 1.5 * CRUISE_SPEED;
pub const TURBO_FORCE: f64 = 30_000.0 * PACE_SCALE;
pub const TURBO_CHARGE_RATE: f64 = 0.04;
pub const TURBO_CHARGE_ANGLE_RATE: f64 = 0.15;
pub const TURBO_DRAIN_RATE: f64 = 0.5;
pub const LAUNCH_WINDOW: f64 = 0.40;
pub const LAUNCH_SHARPNESS: f64 = 1.3;
pub const LAUNCH_SPEED: f64 = 32.0 * PACE_SCALE;
pub const PAD_BOOST_SCALE: f64 = 0.5;

/// Per-lobby physics tuning: defaults match the consts above, but any field can
/// be overridden at lobby creation (see `from_overrides`). Threaded into the
/// simulation so a lobby runs entirely on its own tweaked values.
#[derive(Clone, Copy, Debug)]
#[allow(non_snake_case)]
pub struct Tuning {
    pub PACE_SCALE: f64,
    pub MASS: f64,
    pub INERTIA_X: f64,
    pub INERTIA_Y: f64,
    pub INERTIA_Z: f64,
    pub COM_Y: f64,
    pub GRAVITY: f64,
    pub THROTTLE_FORCE: f64,
    pub REVERSE_FORCE: f64,
    pub BRAKE_FORCE: f64,
    pub BRAKE_MIN_SPEED: f64,
    pub NORMAL_LINEAR_DAMPING: f64,
    pub DRIFT_LINEAR_DAMPING: f64,
    pub DRIFT_MIN_SPEED: f64,
    pub MAX_TURN_RATE_GRIP: f64,
    pub MAX_TURN_RATE_DRIFT: f64,
    pub STEER_P_GAIN: f64,
    pub GRIP_LAT_ACCEL: f64,
    pub DRIFT_REDIRECT_RATE: f64,
    pub DRIFT_FLOOR_SPEED: f64,
    pub DRIFT_SPEED_PENALTY: f64,
    pub SLIP_BREAK_DEG: f64,
    pub SLIP_BREAK_HARD_DEG: f64,
    pub DRIFT_EFFORT_SPEED_REF: f64,
    pub SLIP_EXIT_DEG: f64,
    pub DRIFT_FLICK_RATE: f64,
    pub DRIFT_FLICK_BLEND: f64,
    pub GRIP_BLEND_RATE: f64,
    pub GRIP_BLEND_EXIT_RATE: f64,
    pub SPIN_GUARD_DEG: f64,
    pub SPIN_LIMIT_DEG: f64,
    pub SPIN_RESTORE_RATE: f64,
    pub UPRIGHT_GAIN: f64,
    pub UPRIGHT_DAMP: f64,
    pub GROUND_ALIGN_MIN_NY: f64,
    pub SUSP_REST_LEN: f64,
    pub SUSP_MAX_LEN: f64,
    pub SUSP_STIFFNESS: f64,
    pub SUSP_DAMP: f64,
    pub AIRROLL_RANGE: f64,
    pub AIRROLL_AIM_LATERAL: f64,
    pub AIRROLL_PULL_SPEED: f64,
    pub AIRROLL_RECOVER_TIME: f64,
    pub AIRROLL_RECOVER_GAIN: f64,
    pub AIRROLL_RECOVER_DAMP: f64,
    pub AIRROLL_SPIN: f64,
    pub AIRROLL_DODGE_SPEED: f64,
    pub COYOTE_GROUND_SECS: f64,
    pub JUMP_SPEED: f64,
    pub MOTION_DIRECTION_EPSILON: f64,
    pub BOOST_CHARGE_RATE: f64,
    pub BOOST_CHARGE_ANGLE_RATE: f64,
    pub BOOST_CHARGE_ANGLE_REF_DEG: f64,
    pub BOOST_CHARGE_KNEE: f64,
    pub BOOST_CHARGE_TOP_FACTOR: f64,
    pub BOOST_CHARGE_DECAY: f64,
    pub BOOST_CHARGE_MIN: f64,
    pub BOOST_PEAK_BONUS: f64,
    pub BOOST_DURATION: f64,
    pub BOOST_ALIGN_THRESHOLD_COS: f64,
    pub BOOST_PENDING_TIMEOUT: f64,
    pub BOOST_SUSTAIN_FORCE: f64,
    pub CRUISE_SPEED: f64,
    pub TURBO_PEAK_SPEED: f64,
    pub TURBO_FORCE: f64,
    pub TURBO_CHARGE_RATE: f64,
    pub TURBO_CHARGE_ANGLE_RATE: f64,
    pub TURBO_DRAIN_RATE: f64,
    pub LAUNCH_WINDOW: f64,
    pub LAUNCH_SHARPNESS: f64,
    pub LAUNCH_SPEED: f64,
    pub PAD_BOOST_SCALE: f64,
}

impl Default for Tuning {
    fn default() -> Self {
        Self::from_overrides(&HashMap::new())
    }
}

impl Tuning {
    /// Build from a NAME->value overrides map, re-evaluating each expression in
    /// order so overriding a base value propagates to everything derived from it.
    #[allow(non_snake_case)]
    #[rustfmt::skip]
    pub fn from_overrides(ov: &HashMap<String, f64>) -> Self {
        let pace_scale = ov.get("PACE_SCALE").copied().unwrap_or(2.0);
        let mass = ov.get("MASS").copied().unwrap_or(1300.0);
        let inertia_x = ov.get("INERTIA_X").copied().unwrap_or(3400.0);
        let inertia_y = ov.get("INERTIA_Y").copied().unwrap_or(3200.0);
        let inertia_z = ov.get("INERTIA_Z").copied().unwrap_or(2800.0);
        let com_y = ov.get("COM_Y").copied().unwrap_or(-0.4);
        let gravity = ov.get("GRAVITY").copied().unwrap_or(22.0);
        let throttle_force = ov.get("THROTTLE_FORCE").copied().unwrap_or(14_500.0 * pace_scale);
        let reverse_force = ov.get("REVERSE_FORCE").copied().unwrap_or(2_500.0 * pace_scale);
        let brake_force = ov.get("BRAKE_FORCE").copied().unwrap_or(4_000.0 * pace_scale);
        let brake_min_speed = ov.get("BRAKE_MIN_SPEED").copied().unwrap_or(0.5);
        let normal_linear_damping = ov.get("NORMAL_LINEAR_DAMPING").copied().unwrap_or(0.25);
        let drift_linear_damping = ov.get("DRIFT_LINEAR_DAMPING").copied().unwrap_or(0.15);
        let drift_min_speed = ov.get("DRIFT_MIN_SPEED").copied().unwrap_or(1.5);
        let max_turn_rate_grip = ov.get("MAX_TURN_RATE_GRIP").copied().unwrap_or(1.2);
        let max_turn_rate_drift = ov.get("MAX_TURN_RATE_DRIFT").copied().unwrap_or(4.6);
        let steer_p_gain = ov.get("STEER_P_GAIN").copied().unwrap_or(25_000.0);
        let grip_lat_accel = ov.get("GRIP_LAT_ACCEL").copied().unwrap_or(9.0 * pace_scale);
        let drift_redirect_rate = ov.get("DRIFT_REDIRECT_RATE").copied().unwrap_or(3.0);
        let drift_floor_speed = ov.get("DRIFT_FLOOR_SPEED").copied().unwrap_or(10.0);
        let drift_speed_penalty = ov.get("DRIFT_SPEED_PENALTY").copied().unwrap_or(0.6);
        let slip_break_deg = ov.get("SLIP_BREAK_DEG").copied().unwrap_or(18.0);
        let slip_break_hard_deg = ov.get("SLIP_BREAK_HARD_DEG").copied().unwrap_or(5.0);
        let drift_effort_speed_ref = ov.get("DRIFT_EFFORT_SPEED_REF").copied().unwrap_or(6.0);
        let slip_exit_deg = ov.get("SLIP_EXIT_DEG").copied().unwrap_or(8.0);
        let drift_flick_rate = ov.get("DRIFT_FLICK_RATE").copied().unwrap_or(5.5);
        let drift_flick_blend = ov.get("DRIFT_FLICK_BLEND").copied().unwrap_or(0.6);
        let grip_blend_rate = ov.get("GRIP_BLEND_RATE").copied().unwrap_or(6.0);
        let grip_blend_exit_rate = ov.get("GRIP_BLEND_EXIT_RATE").copied().unwrap_or(3.5);
        let spin_guard_deg = ov.get("SPIN_GUARD_DEG").copied().unwrap_or(68.0);
        let spin_limit_deg = ov.get("SPIN_LIMIT_DEG").copied().unwrap_or(90.0);
        let spin_restore_rate = ov.get("SPIN_RESTORE_RATE").copied().unwrap_or(3.0);
        let upright_gain = ov.get("UPRIGHT_GAIN").copied().unwrap_or(120_000.0);
        let upright_damp = ov.get("UPRIGHT_DAMP").copied().unwrap_or(42_000.0);
        let ground_align_min_ny = ov.get("GROUND_ALIGN_MIN_NY").copied().unwrap_or(0.35);
        let susp_rest_len = ov.get("SUSP_REST_LEN").copied().unwrap_or(0.9);
        let susp_max_len = ov.get("SUSP_MAX_LEN").copied().unwrap_or(1.4);
        let susp_stiffness = ov.get("SUSP_STIFFNESS").copied().unwrap_or(82_000.0);
        let susp_damp = ov.get("SUSP_DAMP").copied().unwrap_or(6_000.0);
        let airroll_range = ov.get("AIRROLL_RANGE").copied().unwrap_or(40.0);
        let airroll_aim_lateral = ov.get("AIRROLL_AIM_LATERAL").copied().unwrap_or(1.0);
        let airroll_pull_speed = ov.get("AIRROLL_PULL_SPEED").copied().unwrap_or(45.0);
        let airroll_recover_time = ov.get("AIRROLL_RECOVER_TIME").copied().unwrap_or(0.45);
        let airroll_recover_gain = ov.get("AIRROLL_RECOVER_GAIN").copied().unwrap_or(320_000.0);
        let airroll_recover_damp = ov.get("AIRROLL_RECOVER_DAMP").copied().unwrap_or(40_000.0);
        let airroll_spin = ov.get("AIRROLL_SPIN").copied().unwrap_or(13.0);
        let airroll_dodge_speed = ov.get("AIRROLL_DODGE_SPEED").copied().unwrap_or(35.0);
        let coyote_ground_secs = ov.get("COYOTE_GROUND_SECS").copied().unwrap_or(0.10);
        let jump_speed = ov.get("JUMP_SPEED").copied().unwrap_or(13.0);
        let motion_direction_epsilon = ov.get("MOTION_DIRECTION_EPSILON").copied().unwrap_or(0.25);
        let boost_charge_rate = ov.get("BOOST_CHARGE_RATE").copied().unwrap_or(0.11);
        let boost_charge_angle_rate = ov.get("BOOST_CHARGE_ANGLE_RATE").copied().unwrap_or(0.36);
        let boost_charge_angle_ref_deg = ov.get("BOOST_CHARGE_ANGLE_REF_DEG").copied().unwrap_or(35.0);
        let boost_charge_knee = ov.get("BOOST_CHARGE_KNEE").copied().unwrap_or(0.667);
        let boost_charge_top_factor = ov.get("BOOST_CHARGE_TOP_FACTOR").copied().unwrap_or(0.25);
        let boost_charge_decay = ov.get("BOOST_CHARGE_DECAY").copied().unwrap_or(2.0);
        let boost_charge_min = ov.get("BOOST_CHARGE_MIN").copied().unwrap_or(0.15);
        let boost_peak_bonus = ov.get("BOOST_PEAK_BONUS").copied().unwrap_or(11.5 * pace_scale);
        let boost_duration = ov.get("BOOST_DURATION").copied().unwrap_or(1.5);
        let boost_align_threshold_cos = ov.get("BOOST_ALIGN_THRESHOLD_COS").copied().unwrap_or(0.9781476);
        let boost_pending_timeout = ov.get("BOOST_PENDING_TIMEOUT").copied().unwrap_or(1.5);
        let boost_sustain_force = ov.get("BOOST_SUSTAIN_FORCE").copied().unwrap_or(16_500.0 * pace_scale);
        let cruise_speed = ov.get("CRUISE_SPEED").copied().unwrap_or(throttle_force / (1000.0 * normal_linear_damping));
        let turbo_peak_speed = ov.get("TURBO_PEAK_SPEED").copied().unwrap_or(1.5 * cruise_speed);
        let turbo_force = ov.get("TURBO_FORCE").copied().unwrap_or(30_000.0 * pace_scale);
        let turbo_charge_rate = ov.get("TURBO_CHARGE_RATE").copied().unwrap_or(0.04);
        let turbo_charge_angle_rate = ov.get("TURBO_CHARGE_ANGLE_RATE").copied().unwrap_or(0.15);
        let turbo_drain_rate = ov.get("TURBO_DRAIN_RATE").copied().unwrap_or(0.5);
        let launch_window = ov.get("LAUNCH_WINDOW").copied().unwrap_or(0.40);
        let launch_sharpness = ov.get("LAUNCH_SHARPNESS").copied().unwrap_or(1.3);
        let launch_speed = ov.get("LAUNCH_SPEED").copied().unwrap_or(32.0 * pace_scale);
        let pad_boost_scale = ov.get("PAD_BOOST_SCALE").copied().unwrap_or(0.5);
        Self {
            PACE_SCALE: pace_scale,
            MASS: mass,
            INERTIA_X: inertia_x,
            INERTIA_Y: inertia_y,
            INERTIA_Z: inertia_z,
            COM_Y: com_y,
            GRAVITY: gravity,
            THROTTLE_FORCE: throttle_force,
            REVERSE_FORCE: reverse_force,
            BRAKE_FORCE: brake_force,
            BRAKE_MIN_SPEED: brake_min_speed,
            NORMAL_LINEAR_DAMPING: normal_linear_damping,
            DRIFT_LINEAR_DAMPING: drift_linear_damping,
            DRIFT_MIN_SPEED: drift_min_speed,
            MAX_TURN_RATE_GRIP: max_turn_rate_grip,
            MAX_TURN_RATE_DRIFT: max_turn_rate_drift,
            STEER_P_GAIN: steer_p_gain,
            GRIP_LAT_ACCEL: grip_lat_accel,
            DRIFT_REDIRECT_RATE: drift_redirect_rate,
            DRIFT_FLOOR_SPEED: drift_floor_speed,
            DRIFT_SPEED_PENALTY: drift_speed_penalty,
            SLIP_BREAK_DEG: slip_break_deg,
            SLIP_BREAK_HARD_DEG: slip_break_hard_deg,
            DRIFT_EFFORT_SPEED_REF: drift_effort_speed_ref,
            SLIP_EXIT_DEG: slip_exit_deg,
            DRIFT_FLICK_RATE: drift_flick_rate,
            DRIFT_FLICK_BLEND: drift_flick_blend,
            GRIP_BLEND_RATE: grip_blend_rate,
            GRIP_BLEND_EXIT_RATE: grip_blend_exit_rate,
            SPIN_GUARD_DEG: spin_guard_deg,
            SPIN_LIMIT_DEG: spin_limit_deg,
            SPIN_RESTORE_RATE: spin_restore_rate,
            UPRIGHT_GAIN: upright_gain,
            UPRIGHT_DAMP: upright_damp,
            GROUND_ALIGN_MIN_NY: ground_align_min_ny,
            SUSP_REST_LEN: susp_rest_len,
            SUSP_MAX_LEN: susp_max_len,
            SUSP_STIFFNESS: susp_stiffness,
            SUSP_DAMP: susp_damp,
            AIRROLL_RANGE: airroll_range,
            AIRROLL_AIM_LATERAL: airroll_aim_lateral,
            AIRROLL_PULL_SPEED: airroll_pull_speed,
            AIRROLL_RECOVER_TIME: airroll_recover_time,
            AIRROLL_RECOVER_GAIN: airroll_recover_gain,
            AIRROLL_RECOVER_DAMP: airroll_recover_damp,
            AIRROLL_SPIN: airroll_spin,
            AIRROLL_DODGE_SPEED: airroll_dodge_speed,
            COYOTE_GROUND_SECS: coyote_ground_secs,
            JUMP_SPEED: jump_speed,
            MOTION_DIRECTION_EPSILON: motion_direction_epsilon,
            BOOST_CHARGE_RATE: boost_charge_rate,
            BOOST_CHARGE_ANGLE_RATE: boost_charge_angle_rate,
            BOOST_CHARGE_ANGLE_REF_DEG: boost_charge_angle_ref_deg,
            BOOST_CHARGE_KNEE: boost_charge_knee,
            BOOST_CHARGE_TOP_FACTOR: boost_charge_top_factor,
            BOOST_CHARGE_DECAY: boost_charge_decay,
            BOOST_CHARGE_MIN: boost_charge_min,
            BOOST_PEAK_BONUS: boost_peak_bonus,
            BOOST_DURATION: boost_duration,
            BOOST_ALIGN_THRESHOLD_COS: boost_align_threshold_cos,
            BOOST_PENDING_TIMEOUT: boost_pending_timeout,
            BOOST_SUSTAIN_FORCE: boost_sustain_force,
            CRUISE_SPEED: cruise_speed,
            TURBO_PEAK_SPEED: turbo_peak_speed,
            TURBO_FORCE: turbo_force,
            TURBO_CHARGE_RATE: turbo_charge_rate,
            TURBO_CHARGE_ANGLE_RATE: turbo_charge_angle_rate,
            TURBO_DRAIN_RATE: turbo_drain_rate,
            LAUNCH_WINDOW: launch_window,
            LAUNCH_SHARPNESS: launch_sharpness,
            LAUNCH_SPEED: launch_speed,
            PAD_BOOST_SCALE: pad_boost_scale,
        }
    }

    /// All tweakable constant names, in file order.
    pub const NAMES: [&'static str; 72] = [
        "PACE_SCALE",
        "MASS",
        "INERTIA_X",
        "INERTIA_Y",
        "INERTIA_Z",
        "COM_Y",
        "GRAVITY",
        "THROTTLE_FORCE",
        "REVERSE_FORCE",
        "BRAKE_FORCE",
        "BRAKE_MIN_SPEED",
        "NORMAL_LINEAR_DAMPING",
        "DRIFT_LINEAR_DAMPING",
        "DRIFT_MIN_SPEED",
        "MAX_TURN_RATE_GRIP",
        "MAX_TURN_RATE_DRIFT",
        "STEER_P_GAIN",
        "GRIP_LAT_ACCEL",
        "DRIFT_REDIRECT_RATE",
        "DRIFT_FLOOR_SPEED",
        "DRIFT_SPEED_PENALTY",
        "SLIP_BREAK_DEG",
        "SLIP_BREAK_HARD_DEG",
        "DRIFT_EFFORT_SPEED_REF",
        "SLIP_EXIT_DEG",
        "DRIFT_FLICK_RATE",
        "DRIFT_FLICK_BLEND",
        "GRIP_BLEND_RATE",
        "GRIP_BLEND_EXIT_RATE",
        "SPIN_GUARD_DEG",
        "SPIN_LIMIT_DEG",
        "SPIN_RESTORE_RATE",
        "UPRIGHT_GAIN",
        "UPRIGHT_DAMP",
        "GROUND_ALIGN_MIN_NY",
        "SUSP_REST_LEN",
        "SUSP_MAX_LEN",
        "SUSP_STIFFNESS",
        "SUSP_DAMP",
        "AIRROLL_RANGE",
        "AIRROLL_AIM_LATERAL",
        "AIRROLL_PULL_SPEED",
        "AIRROLL_RECOVER_TIME",
        "AIRROLL_RECOVER_GAIN",
        "AIRROLL_RECOVER_DAMP",
        "AIRROLL_SPIN",
        "AIRROLL_DODGE_SPEED",
        "COYOTE_GROUND_SECS",
        "JUMP_SPEED",
        "MOTION_DIRECTION_EPSILON",
        "BOOST_CHARGE_RATE",
        "BOOST_CHARGE_ANGLE_RATE",
        "BOOST_CHARGE_ANGLE_REF_DEG",
        "BOOST_CHARGE_KNEE",
        "BOOST_CHARGE_TOP_FACTOR",
        "BOOST_CHARGE_DECAY",
        "BOOST_CHARGE_MIN",
        "BOOST_PEAK_BONUS",
        "BOOST_DURATION",
        "BOOST_ALIGN_THRESHOLD_COS",
        "BOOST_PENDING_TIMEOUT",
        "BOOST_SUSTAIN_FORCE",
        "CRUISE_SPEED",
        "TURBO_PEAK_SPEED",
        "TURBO_FORCE",
        "TURBO_CHARGE_RATE",
        "TURBO_CHARGE_ANGLE_RATE",
        "TURBO_DRAIN_RATE",
        "LAUNCH_WINDOW",
        "LAUNCH_SHARPNESS",
        "LAUNCH_SPEED",
        "PAD_BOOST_SCALE",
    ];
}
