#!/usr/bin/env python3
"""Generate the shared physics-tuning constants for both server and client.

Reads the single source of truth `tuning.txt` and writes:
  - server/src/tuning.rs   (Rust `pub const`s + a runtime `Tuning` struct)
  - client/scripts/tuning.gd (GDScript `static var`s + `apply_overrides`)

so the authoritative simulation (lobby.rs) and the client prediction (player.gd)
can never drift apart. Run with the Windows-friendly `py` launcher:

    py scripts/gen_tuning.py            # regenerate the two files
    py scripts/gen_tuning.py --check    # CI: fail (exit 1) if they're stale

The `EXPR` of each `NAME = EXPR` line is emitted verbatim into both languages,
so it must be valid in each (plain f64 arithmetic + references to earlier NAMEs).

Per-lobby tweaks: both files also expose a way to rebuild every value from an
overrides map (NAME -> value), re-evaluating each expression in order so that
overriding a base (e.g. PACE_SCALE) propagates to everything derived from it.
The Rust `Tuning` struct (one per lobby) and the GDScript static vars hold the
active values; a tweak panel (built from `Tuning.TWEAKABLE`) drives them.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tuning.txt")
RUST = os.path.join(ROOT, "server", "src", "tuning.rs")
GD = os.path.join(ROOT, "client", "scripts", "tuning.gd")

RUST_HEADER = (
    "// @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.\n"
    "// Shared server<->client physics tuning (single source of truth).\n"
    "#![allow(dead_code)]\n"
    "use std::collections::HashMap;\n\n"
)
GD_HEADER = (
    "# @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.\n"
    "# Shared server<->client physics tuning (single source of truth).\n"
    '# Use via: const Tuning = preload("res://scripts/tuning.gd")\n'
    "extends RefCounted\n\n"
)

SECTION_RE = re.compile(r"^#\s*[-=]{2,}\s*(.*?)\s*[-=]*\s*$")


def parse(text):
    """Return [(name, expr, section)] in file order, tracking `# --- Section ---`."""
    consts = []
    section = "General"
    for n, raw in enumerate(text.splitlines(), 1):
        stripped = raw.strip()
        m = SECTION_RE.match(stripped)
        if m and m.group(1):
            section = m.group(1)
            continue
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if "=" not in line:
            raise SystemExit(f"gen_tuning: tuning.txt:{n}: missing '=': {raw!r}")
        name, expr = (part.strip() for part in line.split("=", 1))
        if not name.replace("_", "").isalnum() or not expr:
            raise SystemExit(f"gen_tuning: tuning.txt:{n}: bad entry: {raw!r}")
        consts.append((name, expr, section))
    return consts


def defaults(consts):
    """Evaluate each EXPR in order so we know each constant's numeric default."""
    ns = {}
    for name, expr, _ in consts:
        ns[name] = eval(expr, {"__builtins__": {}}, ns)  # exprs are plain arithmetic
    return ns


def lower_expr(expr, nameset):
    """Lowercase the NAME references in an expr (so `from_overrides` locals — which
    must be lowercase to not collide with the same-named consts — see each other)."""
    return re.sub(
        r"[A-Za-z_][A-Za-z0-9_]*",
        lambda m: m.group(0).lower() if m.group(0) in nameset else m.group(0),
        expr,
    )


def render_rust(consts, defs):
    out = [RUST_HEADER]
    out += [f"pub const {n}: f64 = {e};\n" for n, e, _ in consts]
    nameset = {n for n, _, _ in consts}

    # Runtime per-lobby copy: same values, but rebuildable from an overrides map.
    out.append("\n/// Per-lobby physics tuning: defaults match the consts above, but any field can\n")
    out.append("/// be overridden at lobby creation (see `from_overrides`). Threaded into the\n")
    out.append("/// simulation so a lobby runs entirely on its own tweaked values.\n")
    out.append("#[derive(Clone, Copy, Debug)]\n#[allow(non_snake_case)]\npub struct Tuning {\n")
    out += [f"    pub {n}: f64,\n" for n, _, _ in consts]
    out.append("}\n\n")

    out.append("impl Default for Tuning {\n    fn default() -> Self {\n")
    out.append("        Self::from_overrides(&HashMap::new())\n    }\n}\n\n")

    out.append("impl Tuning {\n")
    out.append("    /// Build from a NAME->value overrides map, re-evaluating each expression in\n")
    out.append("    /// order so overriding a base value propagates to everything derived from it.\n")
    out.append("    #[allow(non_snake_case)]\n")
    out.append("    #[rustfmt::skip]\n")
    out.append("    pub fn from_overrides(ov: &HashMap<String, f64>) -> Self {\n")
    for n, e, _ in consts:
        le = lower_expr(e, nameset)
        out.append(f'        let {n.lower()} = ov.get("{n}").copied().unwrap_or({le});\n')
    out.append("        Self {\n")
    out += [f"            {n}: {n.lower()},\n" for n, _, _ in consts]
    out.append("        }\n    }\n\n")

    # Every tweakable name (for validating/echoing override keys).
    out.append("    /// All tweakable constant names, in file order.\n")
    out.append(f"    pub const NAMES: [&'static str; {len(consts)}] = [\n")
    out += [f'        "{n}",\n' for n, _, _ in consts]
    out.append("    ];\n")
    out.append("}\n")
    return "".join(out)


def render_gd(consts, defs):
    out = [GD_HEADER]
    # Static vars hold the ACTIVE (possibly tweaked) values; defaults are the
    # evaluated numbers (no inter-var references in initialisers — safest order).
    for n, _, _ in consts:
        out.append(f"static var {n} := {defs[n]!r}\n")

    # Metadata for the tweak UI: [name, default, section], file order.
    out.append("\n# [name, default_value, section] for the gameplay-tweak panel.\n")
    out.append("const TWEAKABLE := [\n")
    for n, _, sec in consts:
        out.append(f'\t[{n!r}, {defs[n]!r}, {sec!r}],\n')
    out.append("]\n\n")

    # Rebuild every static var from an overrides dict, re-evaluating expressions in
    # order (so overriding a base propagates to derived values). Call BEFORE cars
    # spawn so player.gd picks the tweaked values up.
    out.append("static func apply_overrides(ov: Dictionary) -> void:\n")
    for n, e, _ in consts:
        out.append(f'\t{n} = ov.get({n!r}, {e})\n')
    # Reset everything back to the file defaults (lobby left / no tweaks).
    out.append("\nstatic func reset() -> void:\n")
    out.append("\tapply_overrides({})\n")
    return "".join(out)


def render(consts):
    defs = defaults(consts)
    return {RUST: render_rust(consts, defs), GD: render_gd(consts, defs)}


def main():
    check = "--check" in sys.argv[1:]
    with open(SRC, encoding="utf-8") as f:
        outputs = render(parse(f.read()))

    stale = []
    for path, content in outputs.items():
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read().replace("\r\n", "\n")
        if check:
            if current != content:
                stale.append(os.path.relpath(path, ROOT))
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)

    if check:
        if stale:
            print("gen_tuning: STALE — run `py scripts/gen_tuning.py`:")
            for p in stale:
                print("  " + p)
            sys.exit(1)
        print("gen_tuning: tuning.rs and tuning.gd are in sync.")
    else:
        print(f"gen_tuning: wrote tuning.rs and tuning.gd from {os.path.relpath(SRC, ROOT)}.")


if __name__ == "__main__":
    main()
