#!/usr/bin/env python3
"""Generate the shared physics-tuning constants for both server and client.

Reads the single source of truth `tuning.txt` and writes:
  - server/src/tuning.rs   (Rust `pub const`s)
  - client/scripts/tuning.gd (a `Tuning` GDScript class)

so the authoritative simulation (lobby.rs) and the client prediction (player.gd)
can never drift apart. Run with the Windows-friendly `py` launcher:

    py scripts/gen_tuning.py            # regenerate the two files
    py scripts/gen_tuning.py --check    # CI: fail (exit 1) if they're stale

The `EXPR` of each `NAME = EXPR` line is emitted verbatim into both languages,
so it must be valid in each (plain f64 arithmetic + references to earlier NAMEs).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tuning.txt")
RUST = os.path.join(ROOT, "server", "src", "tuning.rs")
GD = os.path.join(ROOT, "client", "scripts", "tuning.gd")

RUST_HEADER = (
    "// @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.\n"
    "// Shared server<->client physics tuning (single source of truth).\n"
    "#![allow(dead_code)]\n\n"
)
GD_HEADER = (
    "# @generated by scripts/gen_tuning.py from tuning.txt — DO NOT EDIT.\n"
    "# Shared server<->client physics tuning (single source of truth).\n"
    "# Use via: const Tuning = preload(\"res://scripts/tuning.gd\")\n"
    "extends RefCounted\n\n"
)


def parse(text):
    consts = []
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if "=" not in line:
            raise SystemExit(f"gen_tuning: tuning.txt:{n}: missing '=': {raw!r}")
        name, expr = (part.strip() for part in line.split("=", 1))
        if not name.replace("_", "").isalnum() or not expr:
            raise SystemExit(f"gen_tuning: tuning.txt:{n}: bad entry: {raw!r}")
        consts.append((name, expr))
    return consts


def render(consts):
    rust = RUST_HEADER + "".join(f"pub const {n}: f64 = {e};\n" for n, e in consts)
    gd = GD_HEADER + "".join(f"const {n} := {e}\n" for n, e in consts)
    return {RUST: rust, GD: gd}


def main():
    check = "--check" in sys.argv[1:]
    with open(SRC, encoding="utf-8") as f:
        outputs = render(parse(f.read()))

    stale = []
    for path, content in outputs.items():
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read().replace("\r\n", "\n")
        if check:
            if current != content:
                stale.append(os.path.relpath(path, ROOT))
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)

    if check:
        if stale:
            print("gen_tuning: STALE — run `py scripts/gen_tuning.py`:")
            for p in stale:
                print("  " + p)
            sys.exit(1)
        print("gen_tuning: tuning.rs and tuning.gd are in sync.")
    else:
        print(f"gen_tuning: wrote tuning.rs and tuning.gd from {os.path.relpath(SRC, ROOT)}.")


if __name__ == "__main__":
    main()
